import { motion } from "framer-motion";
import React from "react";
import aboutstyles from "../styles/about.module.css";
import styles from "../styles/terms.module.css";
const Condition = () => {
  return (
    <div className={`${aboutstyles.container}  fluid-container`}>
      <div className={aboutstyles.headerSection}>
        <motion.h1
          initial={{ y: 100, opacity: 0 }}
          animate={{ y: 0, opacity: 1 }}
          transition={{ duration: 1 }}
        >
          Privacy Policy
        </motion.h1>
        <img src="/svg/wave.svg" alt="wave" className={aboutstyles.waveImg} />
      </div>
      <div className={styles.innerContainer}>
        <div>
          <p>
            {`This Privacy Policy describes the policies and procedures of Milo Live Entertainment, ("we", "our" or "us") on the collection, use and disclosure of your information in connection with your use of (the "Site"), our mobile applications, and the services, features, or content we offer (the "Services"). We receive information about you from various sources, including: (i) if you register for an account on the Services, through your user account (your “Account”); (ii) your use of the Services generally; and (iii) from third party websites and services. When you use the Services, you are consenting to the collection, transfer, manipulation, storage, disclosure and other uses of your information as described in this Privacy Policy.`}
          </p>
          <h4>
            1. What Does This Privacy Policy Cover (Scope of our Privacy
            Policy)?
          </h4>
          {`1.1 This Privacy Policy covers the treatment of personally identifiable information ("Personal Data") gathered when you are using or accessing the Services. This Privacy Policy also covers our treatment of any Personal Data that our business partners share with us or that we share with our business partners.
1.2 This Privacy Policy does not apply to the practices of third parties that we do not own or control, including but not limited to any third party websites, services and applications (each a "Third Party Service") that you elect to access through the Services or to individuals that we do not manage or employ. While we attempt to facilitate access only to those Third Party Services that share our respect for your privacy, we cannot take responsibility for the content or privacy policies of those Third Party Services. We encourage you to carefully review the privacy policies of any Third Party Services you access.`}
          <h4>2. What Information Do We Collect About You?</h4>
          {`We collect Personal Data about you when you provide such information directly to us, when third parties such as our business partners or service providers provide us with Personal Data about you, or when Personal Data about you is automatically collected in connection with your use of our Services. The information we gather enables us to improve, understand, and continue to operate the Services. In connection with certain aspects of the Services, we may request, collect and/or display some of your Personal Data. The following sections explain in greater detail the types of information we collect about our users.

2.1 Information You Provide to Us
2.1.1 Account Information:
2.1.1.1 If you create an Account you will provide information that could be Personal Data, including but not limited to, your phone number, name, user name, email address, avatar / profile picture, country of residence and preferences.
2.1.1.2 Additionally, if you register for or access the Services using a Third Party Service (such as your social media account login credentials), we may receive Personal Data that you have made available to share through such Third Party Service, which may include, but not be limited to, your name and your email address. You acknowledge that this information may be personal to you, and by creating an Account and providing Personal Data to us, you allow others, including us, to identify you and therefore may not grant you anonymous access to our Services. We may use your contact information to send you information about our Services. 2.1.2 User Content:
2.1.2.1 Some features of the Services allow you to provide content to the Services, and related Personal Data if you so choose. User content includes, but is not limited to, written comments, and pictures. All content submitted by you to the Services and related data may be retained by us indefinitely, even after you terminate your Account or your access to the Services is terminated. We may continue to disclose such content to third parties in a manner that does not reveal Personal Data, as described in this Privacy Policy.

2.2 Information From Others
2.2.1 As mentioned above, you may be able to register for or access the Services using a Third Party Service, such as your social media account (e.g. Facebook, Twitter, etc.). Occasionally, you can also use your Account on our Services to interact with your accounts on these other Third Party Services. For example, you may be able to access posting and sharing tools on the Services that allow you to post information to your social networks (“Share”) outside of the Services. By using these tools or Third Party Services, you acknowledge that some information (such as your IP address, language preferences, timestamp and identifiers related to your request) may be transmitted to us, and that such information and content is covered by this Privacy Policy. Furthermore, if a tool, such as the Share tool, is operated by a Third Party Service, the Third Party Service that operates the tool may collect information about your browser or online activity, which would be subject to the Third Party Service’s privacy policy and your account settings selected through that Third Party Service. When you use these tools, some of your information from the Services may be shared with the Third Party Service and others. Therefore, we encourage you to read the privacy policies and other policies of any Third Party Services, including without limitation any applicable social networks, that you use in connection with the Services.

2.3 Information Collected Automatically
2.3.1 We automatically receive and record information from your web browser or device, such as your IP address, device ID, user query information and cookie information, when you interact with the Services, including when you search for, select, view or interact with other user content. This information is used to enable us to deliver customized content to you, for fighting spam/malware, to improve the Services, to personalize your experience and also to facilitate collection of data concerning your interaction with the Services (e.g., what links you have clicked on). Your IP address may be used to send you geographically-targeted content and advertisements.

2.3.2 Generally, the Services automatically collect usage information, such as the number and frequency of visitors to the Site and the Services. We may use this data in aggregate form, for example, as a statistical measure or in other anonymous forms, but not in a manner that would identify you personally. This type of aggregate data enables us and third parties authorized by us to figure out how often individuals use parts of the Services so that we can analyze and improve them.
2.4 Location Information
2.4.1 We may request access to your current location – provided by your mobile device using GPS or similar technologies – so that we can provide content that is more suitable to your location. For example, we may share information about the location of your device with advertisers to tailor the advertising you see, to your interests, or present you with offers from the businesses around you. You are free to accept or block access to your location information. You can switch off access to your location at any time through your device settings. The Services may collect and pass to third parties precise geolocation information linked to your mobile device or advertising identifiers and may do so when you use the Services or when the Services run in the background on your device. That information may be used by third parties to customize ads in the Services or in other apps: for instance, if your device is often located at or near movie halls, you might receive offers for tickets (even when you are not at a movie hall). The information also may be used for market or other research regarding aggregated traffic patterns: for instance, a company that analyzes shopping trends might use the information to learn whether more or fewer devices are seen near malls or in other shopping districts. ​ We automatically collect usage information that does not identify an individual user (“Usage Data”). For example, when you download and use the Services on a mobile device, we automatically collect information such as your device type, operating system version and type, certain device settings, device time zone, device carrier, current IP address, applications installed on the device, and platform-specific advertising identifiers. We may also collect location information, such as your device GPS coordinates unless you configure your device operating system settings to prevent our collection of location information. Additionally, each time you use the Site we automatically collect the type of web browser you use, your operating system, your Internet Service Provider, your IP address, the pages you view, and the time and duration of your visits to the Site. We use this information to enhance the services we offer, provide targeted advertising, and to help us understand how people use the Site and Services. Aggregated device data, including location and usage data, is also measured for the purposes of market research. If you do not want this information to be linked to your device, you may go to your device “settings” (which are somewhat different for iOS and Android devices) and opt out of interest-based or personalized advertising. You may also prevent the location from being collected by this or other apps, through your device settings (but this may affect the functionality of certain app features).

2.5 Usage Information
2.5.1 We may collect and store information about your usage of, and interaction with, the Services and Third Party Games (whether or not played on the Services), including, messages, posts, game related information (such as games played, your game scores and how often you play), usage of the Services by geographies, device and connection information (such as a device advertising identifier or MAC address), IP address, device capability, bandwidth, web browser software, referring website, statistics on page views, network type and traffic to and from our websites.
2.6 Information Related to Advertisements, Advertising and the Use of Web Beacons
2.6.1 When we serve an advertisement to your device, we collect information about your interaction with this advertisement to help us evaluate the performance of the advertisement that we show, such as whether you clicked on it, or installed the advertised product. The third parties that serve these advertisements may also collect other information about your interaction with an advertisement and about your browser or device. While we attempt to facilitate access only to those Third Party Services that share our respect for your privacy, we cannot take responsibility for the content or privacy policies of those Third Party Services. We encourage you to carefully review the privacy policies of any Third Party Services you access.
2.6.2 To support and enhance the Services, we may serve advertisements through the Services. These advertisements are sometimes targeted and served to particular users, including using your IP address to send you geographically-targeted advertisements, and may come from third party companies called "ad networks." Ad networks include third party ad servers, ad agencies, ad technology vendors and research firms. We may also receive anonymized user data from our Agents (defined below), so we can learn and make enhancements to offer you a better experience. Some of these entities may use cookies, web beacons and other technologies to collect information about your use of the Services and other websites, including your IP address, web browser, pages viewed, time spent on pages, links clicked and conversion information. This information may be used by us and others to, among other things, tailor the Services for you (for example, by providing search results in your preferred language), analyze and track data, determine the popularity of certain content, deliver advertising and content targeted to your interests on our Services and other websites and better understand your online activity.
2.6.3 Advertisements served through the Services may be targeted to users who fit a certain general profile category and may be based on anonymized information inferred from information provided to us by a user, including Personal Data (e.g., gender or age), may be based on the Services usage patterns of particular users, or may be based on your activity on Third Party Services. We do not provide Personal Data to any ad networks for use outside of the Services.
2.7 Shared Photos, Videos and Other Communications
2.7.1 The Services allow you to share photos, videos and other communications (such as interactions during games) with other users, and if you choose to share your photos, videos and other communications, such items will be stored on our servers in accordance with our data retention policies. ​ In addition, if you choose to share these items with other Service users, we may not be able to remove them from our servers or make them unavailable to anyone you have shared them with. Sending photos, videos or other communications through the Services is your decision. By choosing to share that information, you should understand that you may no longer be able to control how that information is used and that it may become publicly available (depending in part on your actions or the actions of others with whom you have shared the information). We are not responsible for any use or misuse of information you share. ​ There is no tolerance for objectionable or abusive content, including nudity, illegal products, services, or activities, misleading, deceptive, sensational or excessively violent content, discriminatory practices, tobacco products, drugs, and drug-related products, unsafe supplements, adult content, adult products or services, surveillance equipment, hacking or cracking, work at home schemes. Promoting external links for users to purchase digital content or services outside the Services is prohibited. All violators will be banned. For questions, please contact Support@milolives.com

2.8 Device and Log Information
2.8.1 If you use our Service, we collect information about your device and browser. This may include device information (type of device, operating system version, unique device identifier (such as an advertising identifier), browser type and version, mobile network information) or log information (IP address, MAC address, screen resolution, and referring domain).
2.9 Error Reporting Information
2.9.1 We also collect error-reporting information if the Services crash or hang so that we can investigate the error and improve the stability of the Services for future releases. In general, these reports do not contain personally identifiable information, or only incidentally do so. As part of these error reports, we receive information about the type and version of your device and browser, the device identifier, the time the error occurred, the feature being used and the state of the application when the error occurred. We do not use this information for any purpose other than for investigating and remedying the error.
2.10 Information Collected Using Cookies
2.10.1 Cookies are pieces of text that may be stored to your computer or device through your web browser when you access a website. Your browser stores cookies in a manner associated with each website you visit. We may use cookies to enable our servers to recognize your web browser and tell us how and when you visit the Site and otherwise use the Services.
2.10.2 Our cookies do not, by themselves, contain Personal Data. However, we may match cookies with your Personal Data to identify you, and we may use cookies to identify that your web browser has accessed aspects of the Services and may associate that information with your Account if you have one.
2.10.3 We may allow third party web analytics service providers to use cookies or similar technologies to collect information about your use of the Services. We use Google Analytics, a service provided by Google, Inc. (“Google”) to help us understand how users use the Services and to enhance your experience when you use the Services. For more information on Google’s privacy practices, please go to and to opt out of data recording and analysis by Google Analytics on the Services, please visit
2.10.4 Most browsers have an option for turning off the cookie feature, which will prevent your browser from accepting new cookies, as well as (depending on the sophistication of your browser software) allowing you to decide on acceptance of each new cookie in a variety of ways. We strongly recommend that you leave cookies active, because they enable you to take advantage of the most attractive features of the Services.
2.10.5 This Privacy Policy covers our use of cookies only and does not cover the use of cookies by third parties. We do not control when or how third parties place cookies on your computer or device. For example, third party websites to which a link points may set cookies on your computer or device.
2.11 Aggregate Information
2.11.1 We collect statistical information about how both unregistered and registered users, collectively, use the Services ("Aggregate Information"). Some of this information is derived from Personal Data. This statistical information is not Personal Data and cannot be tied back to you, your Account, or your web browser.
2.12 Personal Data of Children
2.12.1 As noted in the Terms of Use, we do not knowingly collect or solicit Personal Data from anyone under the age of 18. If you are under 18, please do not attempt to register for the Services or send any Personal Data about yourself to us. If we learn that we have collected Personal Data from a child under age 18, we will delete that information as quickly as possible. If you believe that a child under 18 may have provided us Personal Data, please contact us at Support@milolives.com.`}
          <h4>3. How, and With Whom, Is My Information Shared?</h4>
          {`The Services are designed to help you share appropriate information only with others. As a result, some of the information generated through the Services is shared publicly or with Third Party Services. What information is shared publicly depends on your privacy settings. The following sections explain in greater detail the ways in which we may share your information. We do not sell your Personal Data.
3.1 How We Use Information
3.1.1 In addition to using your information to provide you with the Services that you request, we use or may disclose your personally identifiable information as follows: To verify your identity; To connect you with others as enabled by the Services; To share your Profile with others on the Services in accordance with your account settings; To allow your use of certain features of the Services that may be offered from time to time (such as games, animations, etc.) and to help customize your user experience; To show you the names and profiles of the contacts with whom you communicate and to show your name and profile to persons with whom you communicate on the Services; To manage your account, deliver to you any administrative notices, updates, notifications, alerts and communications relevant to your use of the Services; To provide you with relevant content that you requested, using information that you allow us to collect from you or that you provide to a social media provider with which your account is connected, such as information regarding your and your contacts’ respective locations; To share information about the games you play on our Services (your scores or your experience), with your contacts according to your settings; To understand
(i) how you use the different features of the Services,
(ii) what your preferences are – for example, what type of broadcasts you like to watch or what type of products you like to view or purchase, and
(iii) how to make suggestions and recommendations of things (for example, games and products) you may be interested in; To keep your list of contacts up to date – for example, when new users join; To solicit information from you, including through surveys; To contact you via email, SMS or otherwise for the purpose of informing you about new products, services or promotions offered by Us (you can opt-out of such emails by clicking on the unsubscribe link, withhold your consent to receive an SMS or reply stop to an SMS in order not to receive future SMSs); For internal operations, including troubleshooting problems, data analysis, testing, research, improvements to the Service, detecting and protecting against error, fraud or other illegal activity; When we believe it is appropriate to investigate, prevent, or take action regarding illegal or suspected illegal activities.

3.2 Public Information About You and Your Activity on the Services
3.2.1 User profile information that you choose to provide, including your username, information about yourself, your avatar/profile picture and a description of your channel may be displayed to other users to facilitate user interaction within the Services. This information will be displayed to other users depending on your privacy settings. We will not directly reveal user email addresses to other users.
3.2.2 Some of your activity on and through the Services is public by default. This may include, but is not limited to, content you have posted publicly on the Site or otherwise through the Services. For registered users, all content you post publicly (or privately) will be associated with your account. Unregistered users will not have this association, but information concerning their use of the Services (such as what pages they have visited) may be tracked through the use of cookies and stored by us.
3.2.3 Please remember that if you choose to provide Personal Data using certain public features of the Services, then that information is governed by the privacy settings of those particular features and may be publicly available. Individuals reading such information may use or disclose it to other individuals or entities without our control and without your knowledge, and search engines may index that information. We therefore urge you to think carefully about including any specific information you may deem private in content that you create or information that you submit through the Services.
3.3 Information Shared Through Third Party Services
3.3.1 You may access other Third Party Services through the Services, for example by clicking on links to those Third Party Services from within our Services. We are not responsible for the privacy policies and/or practices of these Third Party Services, and you are responsible for reading and understanding those Third Party Services' privacy policies. This Privacy Policy only governs information collected on the Services.
3.4 Information Shared In Connection with Our Service Providers
3.4.1 We employ and contract with people and other entities that perform certain tasks on our behalf and who are under our control (our "service providers"). We may need to share Personal Data with our service providers in order to provide products or services to you. Unless we tell you differently, our service providers do not have any right to use Personal Data or other information we share with them beyond what is necessary to assist us. You hereby consent to our sharing of your Personal Data with our service providers.
3.4.2 For example, these service providers would include: SMS and email providers who deliver the authentication SMS or email to you when you register with the Services and with whom We share your phone number or email. Entities who provide services or functions on our behalf, such as hosting, business analytics, customer service, collecting or processing credit and debit card information and payments, marketing, distribution of surveys and fraud prevention.
3.5 Information Shared In Connection with Related Services
3.5.1 While we collect and store IP address and device ID information, that information is not made public. We do at times, however, share this information with our service providers and as otherwise specified in this Privacy Policy.
3.5.2 We also share Aggregate Information with our partners, service providers and other persons with whom we conduct business, including advertisers and investors. Aggregate or anonymous information is information that does not, on its own, identify you personally. For example, we may tell our advertisers the number of users our app receives or share anonymous identifiers (such as device advertising identifiers or hashed email addresses) with advertisers and business partners. This information does not contain any personally identifiable information.
3.5.3 We share this type of statistical data so that our partners can understand in what manner and how often people use our Services and their services or websites, which facilitates improving both their services and how our Services interface with them. In addition, these third parties may share with us non-private, aggregated or otherwise non-Personal Information about you that they have independently developed or acquired.
3.6 Business Partners
3.6.1 We have relationships with other companies, such as game developers, where we serve as the publisher or distributor of the applications, products, or services developed by those third parties. In this case, both We and that third party may have access to certain information about your use of that third party's application, product, or service. For example We may host a third party’s game through its Service, and would have access to some information about your use of that game (such as whether you play it or not, your game scores and how often you play), while the third party would have access to your score, other information about your use of that game and your profile. In this case, the information that we collect is subject to this Privacy Policy and the information that the third party collects is subject to that third party’s privacy policy.`}
          <h4>4. What Choices Do I Have Regarding My Information?</h4>
          {`4.1 Access and Control Your Personal Data
4.1.1 If you are a registered user, you can access information associated with your Account by logging into the Services. Registered and unregistered users can access and delete cookies through their web browser settings.
4.1.2 You can use many of the features of the Services without registering, thereby limiting the type of information that we collect.
4.1.3 You can always opt not to disclose certain information to us, but please note that such information may be needed to take advantage of some of our features.
4.1.4 You can opt-out of certain cookies and tracking technologies by following the steps set forth in the section titled “Information Collected Using Cookies” above.
4.1.5 Your browser may offer you a “Do Not Track” or “DNT” option, which allows you to signal to operators of websites, and web applications, and services that you do not wish such operators to track certain of your online activities over time and across different websites.
4.2.2 Reset your mobile device’s advertising identifier or set it to opt out of targeted advertising:
4.2.3 Android: You can reset your advertising ID at any time from the Ads section under Settings on your device, or you can also opt-out of targeting advertising in this same section.
4.2.4 We want you to know that by opting-out of targeted advertising does not mean that you will no longer receive advertising, but just that the advertising that you do receive will not be customized to you and may feel less relevant to you.
4.3 Opt-Out – Promotional Communications
4.3.1 We allow you to choose not to receive promotional email messages from the Services or Our service providers. You may opt-out by following instructions in the message sent by us or our service providers on how to unsubscribe from that particular mailing. You may also opt-out by contacting us at.
4.4 Delete Your Account
4.4.1 Should you ever decide to delete your Account, you may do so by emailing Support@milolives.com. Please note that we will need to verify that you have the authority to delete the Account. If you terminate your Account, any association between your Account and information we store will no longer be accessible through your Account. However, given the nature of sharing on the Services, any public activity on your Account prior to deletion will remain stored on our servers and may remain accessible to the public.`}
          <h4>5. How Long Do We Retain Your Personal Data?</h4>
          {`5.1 We retain Personal Data about you for as long as you have an open account with us or as otherwise necessary to provide you Services. In some cases, we retain Personal Data for longer, if doing so is necessary to comply with our legal obligations, resolve disputes or collect fees owed, or is otherwise permitted or required by applicable law, rules or regulation. Afterwards, we retain some information in a depersonalized or aggregated form but not in a way that would identify you personally.`}
          <h4>6. Is the Information About Me Secure?</h4>
          {`6.1 Your Account information will be protected by a password for your privacy and security. You need to prevent unauthorized access to your Account and Personal Data by selecting and protecting your password appropriately and limiting access to your computer and browser by signing off after you have finished accessing your Account. 6.2 We seek to protect Account information to ensure that it is kept private; however, we cannot guarantee the security of any Account information. We store all of our information, including your IP address information, using industry-standard security techniques. We do not guarantee or warrant that such techniques will prevent unauthorized access to information about you that we store, Personal Data or otherwise. Unauthorized entry or use, hardware or software failure, and other factors, may compromise the security of user information at any time.`}
          <h4>7. Where Is My Data Stored And What About Data Transfer?</h4>
          {`7.1 Your information may be stored and processed in any country in which we maintain facilities, including outside of India or India. In this regard, or for purposes of sharing or disclosing data as described in this Privacy Policy, We reserve the right to transfer information outside of your country. By using the Services, you consent to any such transfer of information outside of your country. In addition, by using the Services (which are governed by India law, this Privacy Policy and our Terms of Use), you consent to be governed by India law for these purposes and in connection with your use of the Services.`}
          <h4>
            8. What Happens When There Are Changes to this Privacy Policy?
          </h4>
          {`8.1 We may amend this Privacy Policy from time to time. Use of information we collect now is subject to the Privacy Policy in effect at the time such information is collected. If we make changes in the way we collect or use information, we will notify you by posting an announcement on the Services and/or by sending you an email. A user is bound by any changes to the Privacy Policy when he or she uses the Services after such changes have been first posted.`}
          <h4>9. What If I Have Questions or Concerns?</h4>
          {`9.1 If you have any questions or concerns regarding privacy using the Services, please send us a detailed message to Support@milolives.com. We will make every effort to resolve your concerns.`}
        </div>
      </div>
    </div>
  );
};

export default Condition;
